# Form implementation generated from reading ui file 'voteSafe1.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow) -> None:
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("border-color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 255, 127);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.radioBtnCand1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioBtnCand1.setGeometry(QtCore.QRect(20, 90, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnCand1.setFont(font)
        self.radioBtnCand1.setStyleSheet("color: rgb(0, 170, 0);")
        self.radioBtnCand1.setObjectName("radioBtnCand1")
        self.inputVoterIDNumb = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputVoterIDNumb.setGeometry(QtCore.QRect(290, 340, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inputVoterIDNumb.setFont(font)
        self.inputVoterIDNumb.setStyleSheet("border: 2px solid rgb(0, 170,0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   \n"
"")
        self.inputVoterIDNumb.setObjectName("inputVoterIDNumb")
        self.radioBtnCand2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioBtnCand2.setGeometry(QtCore.QRect(20, 140, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnCand2.setFont(font)
        self.radioBtnCand2.setStyleSheet("color: rgb(0, 170, 0);\n"
"")
        self.radioBtnCand2.setObjectName("radioBtnCand2")
        self.radioBtnWI = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioBtnWI.setGeometry(QtCore.QRect(20, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioBtnWI.setFont(font)
        self.radioBtnWI.setStyleSheet("color: rgb(0, 170, 0);")
        self.radioBtnWI.setObjectName("radioBtnWI")
        self.inputWI = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputWI.setGeometry(QtCore.QRect(290, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inputWI.setFont(font)
        self.inputWI.setStyleSheet("border: 2px solid rgb(0, 170, 0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.inputWI.setObjectName("inputWI")
        self.labelVoterIDNumb = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelVoterIDNumb.setGeometry(QtCore.QRect(20, 340, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelVoterIDNumb.setFont(font)
        self.labelVoterIDNumb.setStyleSheet("color: rgb(0, 170, 0);")
        self.labelVoterIDNumb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelVoterIDNumb.setObjectName("labelVoterIDNumb")
        self.labelMessage = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelMessage.setGeometry(QtCore.QRect(10, 480, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelMessage.setFont(font)
        self.labelMessage.setStyleSheet("color: rgb(255, 0, 0);\n"
"border: 2px solid rgb(0, 170,0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   ")
        self.labelMessage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.btnSubmitVote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSubmitVote.setGeometry(QtCore.QRect(190, 400, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnSubmitVote.setFont(font)
        self.btnSubmitVote.setStyleSheet("border: 2px solid rgb(0, 170,0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   \n"
"color: rgb(0,170,0);")
        self.btnSubmitVote.setObjectName("btnSubmitVote")
        self.inputAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputAge.setGeometry(QtCore.QRect(290, 270, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inputAge.setFont(font)
        self.inputAge.setStyleSheet("border: 2px solid rgb(0, 170,0);\n"
"border-radius: 4px;  /* Optional */\n"
"padding: 4px;   \n"
"")
        self.inputAge.setObjectName("inputAge")
        self.labelAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAge.setGeometry(QtCore.QRect(20, 270, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelAge.setFont(font)
        self.labelAge.setStyleSheet("color: rgb(0, 170, 0);")
        self.labelAge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelAge.setObjectName("labelAge")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VoteSafe"))
        self.labelTitle.setText(_translate("MainWindow", "VoteSafe"))
        self.radioBtnCand1.setText(_translate("MainWindow", "John"))
        self.radioBtnCand2.setText(_translate("MainWindow", "Jane"))
        self.radioBtnWI.setText(_translate("MainWindow", "Write-In Candidate"))
        self.labelVoterIDNumb.setText(_translate("MainWindow", "Voter ID"))
        self.labelMessage.setText(_translate("MainWindow", "Please cast your vote"))
        self.btnSubmitVote.setText(_translate("MainWindow", "Submit Vote"))
        self.labelAge.setText(_translate("MainWindow", "Age(must be 18 to vote)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
